name: CI
run-name: CI on ${{ github.ref }} on ${{ github.sha }}
on:
  push:
    branches:
     - main
jobs:
  Build-And-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libavutil58 libavcodec-dev libavformat-dev libswscale-dev libswresample-dev
          version: 1.2
          execute_install_scripts: true
      - name: CMake config & build
        run:  |
          cmake -B build -DCMAKE_BUILD_TYPE=Release .
          cmake --build build --parallel 4
      - name: Run test
        run: ./build/tools/test/tests
      - name: Run benchmark
        run: ./build/tools/benchmark/benchmarks
