name: pre-commit

on:
  pull_request:

jobs:
  Build-And-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg
          version: 1.0
          execute_install_scripts: true
      - name: CMake config & build
        run:  |
          export PKG_CONFIG_PATH="/usr/local/x86_64-linux-gnu/lib/pkgconfig"
          cmake -B build .
          cmake --build build --parallel 4
