name: pre-commit

on:
  pull_request:

jobs:
  Build-And-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libavutil58 libavcodec-dev libavformat-dev libswscale-dev libswresample-dev
          version: 1.2
          execute_install_scripts: true
      - name: CMake config & build
        run:  |
          cmake -B build .
          cmake --build build --parallel 4
