name: pre-commit

on:
  pull_request:

jobs:
  Build-And-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: install ffmpeg
        - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg
          version: 1.0
      - run:  mkdir build
      - run:  cd build
      - name: Run Cmake Config step
        run:  cmake ../ray-tracing
      - name: Run build
        run:  cmake --build . --parallel 4
